version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: estoque_db
    restart: always
    environment:
      POSTGRES_USER: estoque
      POSTGRES_PASSWORD: estoque
      POSTGRES_DB: estoque_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./flyway/sql:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network

  ecommerce-estoque:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ecommerce-estoque
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8000:8000"
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge